name: Rust

on:
  push:
    branches: [ "master", "github-actions" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-Linux:

    runs-on: fedora-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
      run: cargo build --verbose --release
      run: cargo zigbuild --verbose --target aarch64-apple-darwin 
      run: cargo zigbuild --verbose --release --target aarch64-apple-darwin 
      run: cargo zigbuild --verbose --target x86_64-apple-darwin 
      run: cargo zigbuild --verbose --release --target x86_64-apple-darwin
      run: cargo build --verbose --target x86_64-pc-windows-gnu
      run: cargo build --verbose --release --target x86_64-pc-windows-gnu
    - name: Run tests
      run: cargo test --verbose