name: Rust

on:
  push:
    branches: [ "master", "github-actions" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install mingw-w64
        sudo apt-get install zig

    - name: Install cargo-zigbuild
      run: cargo install --verbose cargo-zigbuild

    - name: Add targets
      run: |
        rustup target add x86_64-pc-windows-gnu
        rustup target add aarch64-apple-darwin
        rustup target add x86_64-apple-darwin

    - name: Build native
      run: |
        cargo build --verbose
        cargo build --verbose --release

    - name: Cross-build macOS
      run: |
        cargo zigbuild --verbose --target aarch64-apple-darwin
        cargo zigbuild --verbose --release --target aarch64-apple-darwin
        cargo zigbuild --verbose --target x86_64-apple-darwin
        cargo zigbuild --verbose --release --target x86_64-apple-darwin

    - name: Cross-build Windows
      run: |
        cargo build --verbose --target x86_64-pc-windows-gnu
        cargo build --verbose --release --target x86_64-pc-windows-gnu
    - name: test
      run: cargo test --verbose